### ISSUE TITLE
Question about the AIDA instalation

### ISSUE THREAD

**Issue by nbeliy** [maswendt/AIDAmri#2]
Hi,
I was asked to install the AIDAmri at my institute, but I quite buggered by the requirements.
Why do you require the exact versions of nipype, lmfit and progressbar2, and niftyreg?
For niftyreg you ask not event for a tag but an exact commit.

Thanks in advance,
Nikita

**Comment by salma1601** [comment]
Dear Aida experts,
I have the same question about `FSL`. It required version is `5.0.1` but I have `FSL 5.0.9` and I do not want to downgrade it. Is it possible to make AIDA work in this case ?

Thanks
Salma

**Comment by nbeliy** [comment]
@salma1601
I guess we will not have an answer here. Did you tried to use AIDA with updated FSL?

**Comment by maswendt** [comment]
Please follow the listed requirements as we haven't tested any other versions and there might be a conflict especially in Python package dependencies. For niftyreg is special as there were many changes in the past and we found only the one listed to work.
