### ISSUE TITLE
Issues for running AIDA

### ISSUE THREAD

**Issue by nbeliy** [maswendt/AIDAmri#3]
1. By trial and error I found that I must run AIDA from exactly bin folder (elsewhere it will not found the subfolders), which is not very convenient. Is there a way to run it from any given place?
2.  In Ubuntu usually there 2 concurrent python installed: python2 and python3, with 2 is default. So when I run `python3 aida_guy.py`, and when it try to search the sub-commands, it runs them with python (which is python2) and obviously it didn't work. The workaround is to create a virtual environment (which will hide all other installations), but again it is not very convenient with constant activation/deactivation.  Can it be fixed?

**Comment by maswendt** [comment]
1. add AIDA bin folder to your PATH
2. we recommend Anaconda, here you can use a dedicated conda environment to install all dependencies
